global:
  provider: digitalocean
  domainName: mahesh.concretecrackgallery.in
  certSecretName: concrete-gallery-tls
  ingress:
    className: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"


